contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #ddamsproteomics channel"
    url: https://nfcore.slack.com/channels/ddamsproteomics
    about: Discussion about the nf-core/ddamsproteomics pipeline
